Repository owncloud/guests, pull requests merged in 2018-10, with the labels that each got.

#239 Fix guest email parsing
  tests/acceptance/features/bootstrap/GuestsContext.php
Labels: 3 - To review, QA-team, dev:acceptance-tests

#240 Use abstract admin username in test scenarios
  tests/acceptance/features/apiGuests/guests.feature
  tests/acceptance/features/bootstrap/GuestsContext.php
Labels: 3 - To review, QA-team, dev:acceptance-tests

#242 Adjust acceptance test method call getLocalMailhogUrl
  tests/acceptance/features/bootstrap/GuestsContext.php
Labels: 3 - To review, QA-team, dev:acceptance-tests

#243 Use EventDispatcherInterface instead of EventDispatcher
  controller/userscontroller.php
Labels: 3 - To review

#245 Do not depend on legacy sharing API methods
  appinfo/app.php
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/hooks.php
  lib/mail.php
Labels: 3 - To review

#249 Rework drone acceptance tests like other apps
  .drone.yml
  Makefile
  tests/acceptance/features/bootstrap/GuestsContext.php
Labels: 3 - To review, QA-team, dev:acceptance-tests

#255 Assert email found
  appinfo/info.xml
  tests/acceptance/features/bootstrap/GuestsContext.php
Labels: 3 - To review, QA-team, dev:acceptance-tests

#254 update readme file that contains the white list
  README.md
Labels: 3 - To review

#259 update 0.6.0 version max-version to 11.0.0.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To review, QA-team

#260 Release 0.6.0
  CHANGELOG.md
  README.md
  appinfo/info.xml
Labels: 3 - To review

#261 Release 0.6.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To review

#262 Bump core max-version v11.0.0.0
  appinfo/info.xml
Labels: 3 - To review, QA-team
