Repository owncloud/guests, pull requests merged in 2018-11, with the labels that each got.

#264 [WIP] Remove user_autofocus expectation from paramters list
  templates/form.password.php
Labels: 2 - Developing

#224 Guest users shouldn't be able to create other guest users #114
  appinfo/app.php
  controller/registercontroller.php
  controller/userscontroller.php
  css/personal.css
  lib/AppInfo/Application.php
  tests/acceptance/features/apiGuests/guests.feature
Labels: 3 - To review

#267 Update changelog for 0.7.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To review

#257 Add issue templates
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue_template.md
Labels: 3 - To review

#269 Set max version to 10
  appinfo/info.xml
Labels: 3 - To review

#270 add --remote for running acceptance tests
  Makefile
Labels: 4 - To release, QA-team, dev:acceptance-tests

#271 Adjust acceptance test steps changed in core
  tests/acceptance/features/apiGuests/guests.feature
Labels: 3 - To review, QA-team, dev:acceptance-tests

#272 Adjust user creation test steps
  tests/acceptance/features/apiGuests/guests.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests
