Repository owncloud/guests, pull requests merged in 2019-03, with the labels that each got.

#314 Release 0.8.0
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3 - To review

#315 Add Pdf Viewer to default whitelist
  lib/AppWhitelist.php
Labels: 3 - To review, enhancement

#316 Drop PHP 5.6
  .drone.yml
Labels: 3 - To review, QA-team

#317 Adjust composer files and app core min-version for 'drop PHP 5.6'
  appinfo/info.xml
  composer.json
  composer.lock
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-team

#318 Fix high DB load on inGroup() and getUsersGroups() calls
  lib/GroupBackend.php
  tests/unit/GroupBackendTest.php
Labels: 4 - To release, blue-ticket, bug, p3-medium, sev3-medium

#320 Update yarn deps
  package.json
  yarn.lock
Labels: 3 - To review
