Repository owncloud/guests, pull requests merged in 2020-06, with the labels that each got.

#417 [Tests-only] Fix failing tests after core changes
  tests/acceptance/features/webUIGuests/guests.feature
Labels: 3 - To review, QA-team

#408 [Tests-Only] Update phpstan to latest version
  .drone.star
  lib/Controller/SettingsController.php
  lib/Controller/UsersController.php
  lib/Mail.php
  phpstan.neon
Labels: 4 - To release, QA-team

#418 Updating bamarni/composer-bin-plugin (1.4.0 => 1.4.1)
  composer.lock
Labels: 3 - To review, dependencies
