Repository owncloud/guests, pull requests merged in 2020-04, with the labels that each got.

#406 Drop PHP 7.1
  .drone.star
  composer.json
  composer.lock
Labels: 3 - To review, QA-team

#407 Update phpstan to 0.12
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 3 - To review

#410 [Tests-Only] Bump phan 2.7 & Run phan in CI
  .drone.star
  lib/Controller/RegisterController.php
  lib/Controller/UsersController.php
  lib/Mail.php
  vendor-bin/phan/composer.json
Labels: QA-team

#411 Implement phpunit v8
  vendor-bin/behat/composer.json
Labels: 4 - To release, QA-team

#412 Adjust drone pipelines for PHP 7.4
  .drone.star
  .gitignore
Labels: 3 - To review, QA-team
